# 2024 Day 8 Tests
from day08 import parse_sample

sample_1 = """..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
.........."""

def test_parse_sample():
    parsed_sample_1 = parse_sample(sample_1)
    assert len(parsed_sample_1) == 10
    assert len(parsed_sample_1[0]) == 10
